import React, { useState, useEffect, use } from "react";
import { toast } from "sonner";
import { useTournamentDetail } from "../../hooks/useTournamentDetail";

import { useParams } from "react-router-dom";
import { useUpdateScore } from "../../hooks/useUpdateScore";
import { useLocation, useNavigate } from "react-router-dom";
import { useCreateKnockoutList } from "../../hooks/useCreateKnockoutList";
import { useSelector } from "react-redux";
import apiClient from "../../services/api/axiosInstance.js";
import {
  Award,
  Calendar,
  ChevronDown,
  Flame,
  MapPin,
  Settings,
  Table,
  Target,
  Trophy,
  CheckCircle, Clock,
  Download,
  Save,
} from "lucide-react";
import AppBackground from "../../components/AppBackground";
import PageHeader from "../../components/PageHeader";
import { useMultipleUpdateScore } from "../../hooks/useMultipleUpdateScore";
import ConfirmModal from "../../components/AlertView";
import { clearUnneededThirdSet, isThirdSetNeeded } from "../../../utils/helpers/matchUtils";

const MatchHome = () => {
  const location = useLocation();
  const state = location.state || {};
  const [groups, setGroups] = useState(null);
  const [matches, setMatches] = useState({});
  const [showConfirm, setShowConfirm] = useState(false);
  const [pendingMatchId, setPendingMatchId] = useState(null);


  const [selectedGroup, setSelectedGroup] = useState("all"); // "all" = show all groups
  const { tournamentId } = useParams();
  const navigate = useNavigate();

  const { handleTournamentDetail, isLoading: isTournamentDetailLoading } =
    useTournamentDetail(tournamentId, "Admin");

  const {
    handleScore,
    isLoading: isScoreLoading,
    isError: isScoreError,
    isSuccess: isScoreSuccess,
  } = useUpdateScore();

  const { handleMultipleScore } = useMultipleUpdateScore();

  const tournamentDetail = handleTournamentDetail();

  useEffect(() => {
    if (tournamentDetail?.groups && tournamentDetail?.matches) {
      setGroups(tournamentDetail.groups); // now groups = { A: [...], B: [...], ... }

      setMatches(tournamentDetail.matches); // now matches = { A: [...], B: [...], ... }
    }
  }, [tournamentDetail]);

  const handleSetChange = (matchId, setIdx, teamKey, value) => {
    console.log("Handle Set Change Called:", matchId, setIdx, teamKey, value);
    setMatches((prev) =>
      prev.map((m) => {
        if (m._id === matchId) {
          const updatedScores = m.scores.map((scoreObj) => {
            const updatedSets = scoreObj.sets.map((set, idx) =>
              idx === setIdx ? { ...set, [teamKey]: Number(value) } : set
            );
            return { ...scoreObj, sets: clearUnneededThirdSet(updatedSets) };
          });
          return { ...m, scores: updatedScores };
        }
        return m;
      })
    );
  };

// Download the group-stage schedule + court scoresheets (same PDF layout as
// round robin). Generated by the server on demand.
const handleDownload = async () => {
  const id = toast.loading("Preparing PDF...");
  try {
    const res = await apiClient.get(`/admin/score-sheet-pdf/${tournamentId}`, { responseType: "blob" });
    const disposition = res.headers?.["content-disposition"] || "";
    const fileName = /filename="([^"]+)"/.exec(disposition)?.[1] || "Match_Schedule.pdf";

    const url = window.URL.createObjectURL(res.data);
    const link = document.createElement("a");
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.URL.revokeObjectURL(url);
    toast.success("PDF downloaded", { id });
  } catch (error) {
    console.error("Download failed:", error);
    let message = "Failed to download PDF";
    // Error bodies come back as a Blob because of responseType: "blob"
    try {
      const text = await error?.response?.data?.text?.();
      message = JSON.parse(text)?.message || message;
    } catch {
      /* keep default message */
    }
    toast.error(message, { id });
  }
};

  const updateAllScore = async () => {
    if (!matches) {
      toast.error("Match not found");
      return;
    }
    console.log("All MAtch", matches);

    const payloadMatches = [];
    for (const match of matches) {
      // Check for any set where home and away scores are the same and > 0
      const hasSameScore = match.scores[0].sets.some(
        (set) => set.home === set.away && set.home > 0
      );

      if (hasSameScore) {
        toast.error("Cannot save: A set has the same score for both teams.");
        return; // block saving
      }
      // Check that every set has at least one team scoring 21 or more
      const isValidSetScore = match.scores[0].sets.every((set) => {
        const bothZero = set.home === 0 && set.away === 0;
        const oneReached21 = set.home >= 21 || set.away >= 21;

        return bothZero || oneReached21;
      });

      if (!isValidSetScore) {
        toast.error("Each set must have at least one team scoring 21 points.");
        return; // block saving
      }

      if (match.status != "finished") {
        match.scores[0].sets.every((set) => {
          if (set.home > 0 || set.away > 0) {
            payloadMatches.push({
              matchId: match._id,
              scores: match.scores,
              group: match.group,
              teamsHome: match.teamsHome,
              teamsAway: match.teamsAway,
            });
          }
        });
      }
    }

    console.log("Group save objects", payloadMatches);

    try {
      handleMultipleScore({ matches: payloadMatches });
    } catch (error) {
      toast.error(
        error?.response?.data?.message || "Failed to update match score"
      );
    }
  };

  const updateScore = (matchId) => {
    const match = matches.find((m) => m._id === matchId);

    if (!match) {
      toast.error("Match not found");
      return;
    }

 const hasSameScore = match.scores[0].sets.some(
        (set) => set.home === set.away && set.home > 0
      );

      if (hasSameScore) {
        toast.error("Cannot save: A set has the same score for both teams.");
        return; // block saving
      }
      // Check that every set has at least one team scoring 21 or more
      const isValidSetScore = match.scores[0].sets.every((set) => {
        const bothZero = set.home === 0 && set.away === 0;
        const oneReached21 = set.home >= 21 || set.away >= 21;

        return bothZero || oneReached21;
      });

      if (!isValidSetScore) {
        toast.error("Each set must have at least one team scoring 21 points.");
        return; // block saving
      }



    const hasZeroButOpponentScored = match.scores[0].sets.some(
      ({ home, away }) => (home === 0 && away > 0) || (away === 0 && home > 0)
    );

    if (hasZeroButOpponentScored) {
      setPendingMatchId(matchId);
      setShowConfirm(true);
      return;
    }

    // Direct save if no confirmation needed
    saveMatch(matchId);
  };

  const handleConfirmYes = () => {
    if (!pendingMatchId) return;

    saveMatch(pendingMatchId);
    setPendingMatchId(null);
    setShowConfirm(false);
  };

  const handleConfirmNo = () => {
    setPendingMatchId(null);
    setShowConfirm(false);
  };

  const saveMatch = (matchId) => {
    const match = matches.find((m) => m._id === matchId);
    if (!match) return;

    const payload = {
      ...match,
      matchId: match._id,
    };

    delete payload._id;
    handleScore(payload);
  };



  const handleGotoKnockout = async () => {
    // Navigate to knockout page with top teams
    try {
      console.log("groups", groups);

      const allFinished = groups.every((gp) => {
        // Get all matches for this group
        const groupMatches = matches.filter((m) => m.group === gp._id);

        // Check if all matches in this group are finished
        return groupMatches.every((match) => match.status === "finished");
      });

      if (!allFinished) {
        toast.error(
          "All groups must be finished before creating knockout stage."
        );
        return;
      }

      navigate("/knockout", { state: { teams: topTeams, tournamentId } });
    } catch (error) {
      console.log("Navigation error:", error);
    }
  };

  // Top teams for knockout
  const topTeams = groups
    ? Object.keys(groups).map((key) => groups[key][0])
    : [];


  

  if (!groups) {
    return (
      <AppBackground>
        <div className="min-h-screen flex items-center justify-center text-slate-400">
          Loading tournament data...
        </div>
      </AppBackground>
    );
  }

  const knockoutScheduled = tournamentDetail?.knockoutStatus === "scheduled";

  return (
    <AppBackground>
      <PageHeader
        title="Group Stage"
        subtitle={tournamentDetail?.tournamentName}
        onBack={() => navigate("/setup-tournament")}
        actions={
          <button
            onClick={handleGotoKnockout}
            className="flex items-center gap-2 bg-gradient-to-r from-cyan-500 to-emerald-500 hover:from-cyan-600 hover:to-emerald-600 text-white px-3 sm:px-4 h-10 rounded-xl font-semibold text-sm shadow-lg shadow-cyan-500/30 transition-all"
          >
            <Award className="w-4 h-4" />
            <span className="hidden sm:inline">Go to Knockout</span>
          </button>
        }
      />

      <div className="p-4 sm:p-6 max-w-7xl mx-auto space-y-6">
        {/* Toolbar: group filter + bulk actions */}
        <div className="sticky top-[72px] z-10 bg-slate-800/70 backdrop-blur-xl rounded-2xl border border-slate-700/50 shadow-xl p-3 sm:p-4 flex flex-col sm:flex-row items-stretch sm:items-center gap-3 justify-between">
          <div className="flex items-center gap-3">
            <label className="flex items-center gap-2 text-sm font-medium text-slate-300 whitespace-nowrap">
              <Target className="w-4 h-4 text-cyan-400" />
              Group
            </label>
            <div className="relative flex-1 sm:flex-none">
              <select
                className="w-full sm:w-48 appearance-none bg-slate-900/50 border border-slate-600 rounded-xl px-3.5 py-2.5 pr-10 text-sm text-white [color-scheme:dark] focus:outline-none focus:ring-2 focus:ring-cyan-500 cursor-pointer"
                value={selectedGroup}
                onChange={(e) => setSelectedGroup(e.target.value)}
              >
                <option value="all">All Groups</option>
                {groups.map((gp) => (
                  <option key={gp._id} value={gp.groupName}>
                    {gp.groupName}
                  </option>
                ))}
              </select>
              <ChevronDown className="w-4 h-4 text-slate-400 absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none" />
            </div>
          </div>

          {!knockoutScheduled && (
            <div className="flex gap-2">
              <button
                onClick={handleDownload}
                className="flex-1 sm:flex-none flex items-center justify-center gap-2 h-10 px-4 rounded-xl border border-amber-500/40 bg-amber-500/10 text-amber-300 text-sm font-medium hover:bg-amber-500/20 transition-all"
              >
                <Download className="w-4 h-4" />
                <span>Score Sheet</span>
              </button>
              <button
                onClick={updateAllScore}
                className="flex-1 sm:flex-none flex items-center justify-center gap-2 h-10 px-4 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-500 hover:from-cyan-600 hover:to-blue-600 text-white text-sm font-semibold shadow-lg shadow-cyan-500/30 transition-all"
              >
                <Save className="w-4 h-4" />
                <span>Update All Scores</span>
              </button>
            </div>
          )}
        </div>

        {/* Group Stage */}
        {groups.length > 0 ? (
          <div
            className={`grid grid-cols-1 ${
              groups.length > 1 && selectedGroup === "all" ? "xl:grid-cols-2" : ""
            } gap-6`}
          >
            {groups
              .filter((gp) => selectedGroup === "all" || selectedGroup === gp.groupName)
              .map((gp) => {
                const groupMatches = matches.filter((m) => m.group === gp._id);
                const wide = !(groups.length > 1 && selectedGroup === "all");

                return (
                  <div
                    key={gp._id}
                    className="bg-slate-800/50 backdrop-blur-xl rounded-2xl shadow-xl border border-slate-700/50 overflow-hidden"
                  >
                    <div className="px-5 py-4 bg-gradient-to-r from-cyan-500/20 via-blue-500/10 to-emerald-500/20 border-b border-slate-700/50">
                      <h2 className="text-lg font-semibold text-white flex items-center gap-2">
                        <Trophy className="w-5 h-5 text-cyan-400" />
                        {gp.groupName}
                        <span className="ml-auto text-xs font-normal text-slate-400">
                          {groupMatches.length} match{groupMatches.length !== 1 ? "es" : ""}
                        </span>
                      </h2>
                    </div>

                    {/* Matches */}
                    <div className="p-4 sm:p-5">
                      <h3 className="mb-3 flex items-center gap-2 text-sm font-semibold text-slate-300">
                        <Calendar className="w-4 h-4 text-cyan-400" />
                        Matches
                      </h3>

                      <div
                        className={`grid grid-cols-1 sm:grid-cols-2 ${wide ? "lg:grid-cols-3" : ""} gap-3`}
                      >
                        {groupMatches.map((m) => (
                          <div
                            key={m._id}
                            className="p-4 rounded-xl bg-slate-900/40 border border-slate-700/50 hover:border-cyan-500/40 transition-all flex flex-col"
                          >
                            <div className="flex items-start justify-between gap-2 mb-3">
                              <div className="min-w-0">
                                <div className="font-semibold text-sm text-white break-words">
                                  {m.matchName}
                                </div>
                                <div className="text-xs text-slate-400 flex items-center gap-1.5 mt-1">
                                  <MapPin className="w-3.5 h-3.5" />
                                  {m.court === "" ? "Court" : m.court}
                                </div>
                              </div>
                              <MatchStatus status={m.status} />
                            </div>

                            <div className="space-y-2">
                              {m.scores[0].sets.map((set, idx) => {
                                const isSameScore = set.home === set.away && set.home > 0 && set.away > 0;
                                // Set 3 only opens when sets 1 & 2 are finished and split 1–1.
                                const locked = idx === 2 && !isThirdSetNeeded(m.scores[0].sets);
                                const scoreCls = `w-full min-w-0 bg-slate-900/60 border rounded-lg py-1.5 text-center text-sm text-white [color-scheme:dark] focus:outline-none focus:ring-2 focus:ring-cyan-500 disabled:opacity-40 ${
                                  isSameScore ? "border-red-500" : "border-slate-600"
                                }`;
                                const onScore = (side) => (e) => {
                                  let value = Number(e.target.value);
                                  if (isNaN(value) || value < 0) value = 0;
                                  if (value > 21) value = 21;
                                  handleSetChange(m._id, idx, side, value);
                                };

                                return (
                                  <div key={set._id} className="flex items-center gap-2">
                                    <span className="w-10 flex-shrink-0 text-[11px] uppercase tracking-wide text-slate-500">
                                      Set {idx + 1}
                                    </span>
                                    <input
                                      type="number"
                                      min={0}
                                      max={21}
                                      className={scoreCls}
                                      value={set.home === 0 ? "" : set.home}
                                      disabled={locked}
                                      onChange={onScore("home")}
                                    />
                                    <span className="text-slate-500">:</span>
                                    <input
                                      type="number"
                                      min={0}
                                      max={21}
                                      className={scoreCls}
                                      value={set.away === 0 ? "" : set.away}
                                      disabled={locked}
                                      onChange={onScore("away")}
                                    />
                                  </div>
                                );
                              })}
                            </div>

                            {/* Update Score Button */}
                            {!knockoutScheduled && (
                              <button
                                className="mt-3 w-full flex items-center justify-center gap-2 px-4 py-2 rounded-lg border border-emerald-500/40 bg-emerald-500/10 text-emerald-300 text-sm font-medium hover:bg-emerald-500/20 transition-all"
                                onClick={() => updateScore(m._id)}
                              >
                                <Save className="w-4 h-4" />
                                Update Score
                              </button>
                            )}
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Points Table */}
                    <div className="px-4 sm:px-5 pb-5">
                      <h3 className="mb-3 flex items-center gap-2 text-sm font-semibold text-slate-300">
                        <Award className="w-4 h-4 text-cyan-400" />
                        Standings
                      </h3>

                      <div className="overflow-x-auto rounded-xl border border-slate-700/50">
                        <table className="w-full text-sm">
                          <thead className="bg-slate-900/60 text-slate-400 text-xs uppercase tracking-wide">
                            <tr>
                              <th className="p-3 text-left">#</th>
                              <th className="p-3 text-left">Team</th>
                              <th className="p-3">M</th>
                              <th className="p-3">W</th>
                              <th className="p-3">L</th>
                              <th className="p-3">PF</th>
                              <th className="p-3">PA</th>
                              <th className="p-3">PD</th>
                              <th className="p-3 text-cyan-300">Pts</th>
                            </tr>
                          </thead>
                          <tbody className="divide-y divide-slate-700/50">
                            {gp.standings
                              .slice()
                              .sort((a, b) => {
                                // Sort by totalPoints, then points difference
                                if (b.totalPoints !== a.totalPoints) return b.totalPoints - a.totalPoints;
                                return b.pointsFor - b.pointsAgainst - (a.pointsFor - a.pointsAgainst);
                              })
                              .map((t, idx) => {
                                const teamObj = gp.teams.find((team) => team.teamId === t.teamId);
                                const isQualified = idx < 2;
                                const pd = t.pointsFor - t.pointsAgainst;

                                return (
                                  <tr
                                    key={idx}
                                    className={`text-slate-200 hover:bg-white/5 transition-colors ${
                                      isQualified ? "bg-emerald-500/5" : ""
                                    }`}
                                  >
                                    <td className="p-3">
                                      <span
                                        className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-semibold ${
                                          isQualified
                                            ? "bg-emerald-500 text-white"
                                            : "bg-slate-700 text-slate-300"
                                        }`}
                                      >
                                        {idx + 1}
                                      </span>
                                    </td>
                                    <td className="p-3 whitespace-nowrap">{teamObj?.name || t.teamId}</td>
                                    <td className="p-3 text-center">{t.matchesPlayed}</td>
                                    <td className="p-3 text-center">{t.wins}</td>
                                    <td className="p-3 text-center">{t.losses}</td>
                                    <td className="p-3 text-center">{t.pointsFor}</td>
                                    <td className="p-3 text-center">{t.pointsAgainst}</td>
                                    <td className="p-3 text-center">
                                      <span className={pd >= 0 ? "text-emerald-400" : "text-red-400"}>
                                        {pd > 0 ? "+" : ""}
                                        {pd}
                                      </span>
                                    </td>
                                    <td className="p-3 text-center">
                                      <span className="px-2 py-0.5 rounded-md bg-cyan-500/20 border border-cyan-500/30 text-cyan-200 font-semibold">
                                        {t.totalPoints}
                                      </span>
                                    </td>
                                  </tr>
                                );
                              })}
                          </tbody>
                        </table>
                      </div>
                      {gp.standings.length > 0 && (
                        <p className="text-xs text-slate-400 mt-2 flex items-center gap-1.5">
                          <Trophy className="w-3.5 h-3.5 text-emerald-400" />
                          Top 2 qualify for the knockout stage
                        </p>
                      )}
                    </div>
                  </div>
                );
              })}
          </div>
        ) : (
          <div className="text-center py-16 bg-slate-800/40 backdrop-blur-xl border border-slate-700/50 rounded-2xl">
            <Trophy className="w-12 h-12 text-slate-500 mx-auto mb-3" />
            <p className="text-slate-300 font-medium">No groups available.</p>
          </div>
        )}
      </div>

      <ConfirmModal
        isOpen={showConfirm}
        title="Save Score"
        message="It looks like a team has zero points. Please check the scores!"
        confirmText="Save"
        cancelText="Cancel"
        loading={isScoreLoading}
        onConfirm={handleConfirmYes}
        onCancel={handleConfirmNo}
      />
    </AppBackground>
  );
};

// Dark status pill (the shared StatusBadge is used on light pages).
const MatchStatus = ({ status }) => {
  const s = status?.toLowerCase();
  const [cls, Icon, label] =
    s === "finished"
      ? ["bg-emerald-500/15 border-emerald-500/30 text-emerald-300", CheckCircle, "Finished"]
      : s === "ongoing"
        ? ["bg-cyan-500/15 border-cyan-500/30 text-cyan-300", Flame, "Live"]
        : ["bg-slate-500/15 border-slate-500/30 text-slate-300", Clock, "Scheduled"];
  return (
    <span className={`flex-shrink-0 px-2.5 py-1 rounded-full border text-[11px] font-medium flex items-center gap-1 ${cls}`}>
      <Icon className="w-3 h-3" /> {label}
    </span>
  );
};

export default MatchHome;
